GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/2

###

POST http://localhost:3000/courses
Content-Type: application/json

{
  "name": "NestJS",
  "description": "Descrição do NestJS.",
  "tags": ["nodejs", "nestjs", "framework", "typescript"]
}

###

PATCH http://localhost:3000/courses/3
Content-Type: application/json

{
  "name": "Angular",
  "description": "Descrição completa do Angular.",
  "tags": ["nodejs", "angular", "framework", "typescript"]
}

###

DELETE http://localhost:3000/courses/2